name: Exercicio2

on:
  push:

jobs:
  checkout:
    name: exercicio2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ vars.VARIAVEL }}
          PATH: .
          
